plugins:
  - jekyll-remote-theme

remote_theme: openapi4j/openapi4j

theme: texture
texture:
  title: OpenAPI4J
  tagline: OpenAPI for Java
  style: black
  showPicker: false
  showNav: true
  social_links:
    github:  openapi4j
